### ISSUE TITLE
fpzip 1.0.4 fails to pip install on a fresh python environment

### ISSUE THREAD

**Issue by fcollman** [seung-lab/fpzip#2]
oddly 1.0.4 can be installed if 1.0.2 is installed first, but a fresh conda environment fails for python 3.6.  I think there is something wrong with the packaging. 

 pip install fpzip
Looking in indexes: http://aibs-artifactory.corp.alleninstitute.org/artifactory/api/pypi/pypi-local/simple,https://pypi.python.org/simple/
Collecting fpzip
  Downloading https://files.pythonhosted.org/packages/01/bc/33d7620fc7bd8ab5ed7f1d0bc663e79ebe0622873954d38d4b1d436230f2/fpzip-1.0.4.tar.gz (849kB)
    100% |████████████████████████████████| 849kB 4.8MB/s
No files/directories in /private/var/folders/93/pxx43tfd7nqbr7rbdxxm7jpn4fvqmh/T/pip-install-1692k9ut/fpzip/pip-egg-info (from PKG-INFO)

**Comment by william-silversmith** [comment]
fpzip requires numpy to be installed first. This is due to a deficiency in Python's installation ecosystem. I investigated the installation failures in app engine and it appears to be security related.

**Comment by william-silversmith** [comment]
I also tried reproducing the conda problem on my local machine, but was unable. I might want to try integrating conda into the continuous integration testing.

**Comment by william-silversmith** [comment]
@fcollman I added some binaries for version 1.1.2. Would you want to give it a try again if you're still having the issue?

**Comment by fcollman** [comment]
yes... i can confirm this worked great on os X and ubuntu 16.04
